"""Build the full Godot asset pack: run every export module in one pass.

Wipes godot_assets/ and regenerates it from the sources of record (assets/,
docs/start_screen/, экран_утро_сон/ and git history for the deleted FOR_DEV
journey drop), then writes the combined manifest.json and a README.

Usage: python3 tools/godot_export/export_all.py
"""

import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from godot_export import (  # noqa: E402
    core,
    export_backgrounds,
    export_generic,
    export_journey,
    export_luma,
    export_start_screen,
)

README = """\
# The Sleepy Knight — Godot asset pack

Generated by `tools/godot_export/export_all.py`. Do not edit by hand —
rerun the exporter instead. Copy this folder into a Godot 4 project as
`res://assets/` (the .tres files reference that path).

## Layout

Only art the shipping game actually references is exported — dead variants
(gold/walk heroes, parallax props, result-scene banners, stale mockups) are
deliberately absent.

| Folder          | Contents |
| --------------- | -------- |
| `sprites/`      | hero idle strips and misc sprites (chest, Luma guide) |
| `sprites_1bit/` | the 1-bit e-ink variants (idle heroes, icon, hearts) |
| `icons/`        | single-frame icons (equippable artifacts, cosmetics, hearts, guide book) |
| `atmosphere/`   | DayNightBackground layers (clouds, sun/moon, grass per time of day) |
| `ui/`           | per-screen UI elements as individual PNGs (bag, chest, settings, ...) |
| `journey/`      | night-journey set: sky band, the 5 looped forest tiles, HUD panels, dock buttons, XP strip |
| `start_screen/` | authored-pixel-grid background + candle strip + pressed plaque overlays |
| `luma/`         | fullscreen Luma scenes: background + hand-cut zones (whole-character `luma_*`, ambient `env_*`) |
| `backgrounds/`  | one-texture screens (death, night results, mosaic, tether) |

## Formats

* **Animations** are horizontal strips with uniform frames. Each has a
  `.json` sidecar (`frame_width/frame_height/frames/fps/loop`, optional
  `frame_order` playback sequence) and a ready `SpriteFrames` **`.tres`**
  for `AnimatedSprite2D`.
* **`scene.json`** (luma scenes) lists the background plus every animated
  zone with its pixel `position` — place each zone strip at that offset
  over the background.
* **`manifest.json`** at the root indexes everything, including per-asset
  `meta` notes (anchor boxes on HUD panels, walk strips being left-facing,
  state-driven strips like the XP bar and chest).
* Pixel art (start screen, heroes, icons) must be imported with **nearest**
  filtering; everything is exported at source resolution — scale in-engine.

## Playback notes

* Luma zones: `luma_blink`/`luma_talk` swap the whole character box
  (frame 0 = rest); `env_*` flames loop with ping-pong baked into
  `frame_order`. Blink is a random flash (frame 1 for ~220 ms every
  3-6 s), talk cycles while she speaks.
* Journey forest tiles cycle in `meta.loop_order`, ~10 s per tile; the
  sky is cropped to its detail band — fill below with the `gradient`
  colors from its meta.
* Journey dock buttons are opaque slot-sized tiles cut from `hud_bottom`;
  the blank `plate` gets its label typeset in-engine.
"""


def run_all():
    if os.path.isdir(core.OUT_ROOT):
        shutil.rmtree(core.OUT_ROOT)
    core.MANIFEST.clear()
    export_generic.run()
    export_journey.run()
    export_start_screen.run()
    export_luma.run()
    export_backgrounds.run()
    core.write_manifest()
    with open(os.path.join(core.OUT_ROOT, 'README.md'), 'w', encoding='utf-8') as fh:
        fh.write(README)
    print('README.md written')


if __name__ == '__main__':
    run_all()
