import React, { useEffect, useRef } from 'react'
import { Animated, Easing } from 'react-native'

/** White radial alpha sprite generated by tools/night_slice.py, tinted here. */
const GLOW = require('../../assets/design/gen/night/glow.png')

export interface GlowSpec {
  x: number // glow center in 2160x3840 sheet coords
  y: number
  r: number // radius in sheet px
  color: string
  peak: number // max opacity of the pulse
  mode: 'breathe' | 'flicker'
}

/** Slow sine breathing — sunrise / fog glow. */
function breathe(value: Animated.Value): Animated.CompositeAnimation {
  const half = (toValue: number) =>
    Animated.timing(value, {
      toValue,
      duration: 1700,
      easing: Easing.inOut(Easing.sin),
      useNativeDriver: true,
    })
  return Animated.loop(Animated.sequence([half(1), half(0)]))
}

/** Quick double flash with a long dark pause — lightning. */
function flicker(value: Animated.Value): Animated.CompositeAnimation {
  const jump = (toValue: number, duration: number) =>
    Animated.timing(value, { toValue, duration, useNativeDriver: true })
  return Animated.loop(
    Animated.sequence([
      jump(1, 90),
      jump(0.15, 120),
      jump(0.7, 90),
      jump(0, 260),
      Animated.delay(2200),
    ]),
  )
}

/** Soft radial glow breathing over the sun (or flickering with lightning). */
export function MorningGlow({ spec, k }: { spec: GlowSpec; k: number }) {
  const pulse = useRef(new Animated.Value(0)).current
  useEffect(() => {
    const animation = (spec.mode === 'flicker' ? flicker : breathe)(pulse)
    animation.start()
    return () => animation.stop()
  }, [pulse, spec.mode])
  const size = spec.r * 2 * k
  return (
    <Animated.Image
      source={GLOW}
      style={{
        position: 'absolute',
        left: (spec.x - spec.r) * k,
        top: (spec.y - spec.r) * k,
        width: size,
        height: size,
        tintColor: spec.color,
        opacity: pulse.interpolate({ inputRange: [0, 1], outputRange: [0.04, spec.peak] }),
        transform: [{ scale: pulse.interpolate({ inputRange: [0, 1], outputRange: [1, 1.06] }) }],
      }}
    />
  )
}
