/* eslint-disable max-lines */
// GENERATED FILE — produced by tools/pixelate.py / tools/generate_audio.py.
// Do not edit by hand; rerun the pipeline instead. This manifest is the ONLY
// supported way for UI code to reference game assets (PROMPT C §6).
//
// Multi-frame assets are horizontal strips: frameWidth x frameHeight per
// frame, `frames` frames laid out left to right.

export interface SpriteEntry {
  /** Metro asset reference — pass straight to <Image source={...} />. */
  readonly source: number;
  /** On-disk pixel size of the whole strip (grid size x 4 upscale). */
  readonly width: number;
  readonly height: number;
  readonly frames: number;
  readonly frameWidth: number;
  readonly frameHeight: number;
}

export interface AudioEntry {
  readonly source: number;
  readonly durationSec: number;
  readonly loop: boolean;
}

export const SPRITES = {
  chest: {
    source: require('./sprites/chest.png'),
    width: 576,
    height: 192,
    frames: 3,
    frameWidth: 192,
    frameHeight: 192,
  },
  gravestone: {
    source: require('./sprites/gravestone.png'),
    width: 192,
    height: 192,
    frames: 1,
    frameWidth: 192,
    frameHeight: 192,
  },
  hero_druid: {
    source: require('./sprites/hero_druid.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_gold: {
    source: require('./sprites/hero_druid_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight: {
    source: require('./sprites/hero_knight.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_gold: {
    source: require('./sprites/hero_knight_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage: {
    source: require('./sprites/hero_mage.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_gold: {
    source: require('./sprites/hero_mage_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk: {
    source: require('./sprites/hero_monk.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_gold: {
    source: require('./sprites/hero_monk_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja: {
    source: require('./sprites/hero_ninja.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_gold: {
    source: require('./sprites/hero_ninja_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin: {
    source: require('./sprites/hero_paladin.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_gold: {
    source: require('./sprites/hero_paladin_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger: {
    source: require('./sprites/hero_ranger.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_gold: {
    source: require('./sprites/hero_ranger_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue: {
    source: require('./sprites/hero_rogue.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_gold: {
    source: require('./sprites/hero_rogue_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock: {
    source: require('./sprites/hero_warlock.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_gold: {
    source: require('./sprites/hero_warlock_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>;

export const SPRITES_1BIT = {
  '1bit_heart_empty': {
    source: require('./sprites/1bit/1bit_heart_empty.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  '1bit_heart_full': {
    source: require('./sprites/1bit/1bit_heart_full.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  hero_druid: {
    source: require('./sprites/1bit/hero_druid.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_icon_40: {
    source: require('./sprites/1bit/hero_icon_40.png'),
    width: 160,
    height: 160,
    frames: 1,
    frameWidth: 160,
    frameHeight: 160,
  },
  hero_knight: {
    source: require('./sprites/1bit/hero_knight.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage: {
    source: require('./sprites/1bit/hero_mage.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk: {
    source: require('./sprites/1bit/hero_monk.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja: {
    source: require('./sprites/1bit/hero_ninja.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin: {
    source: require('./sprites/1bit/hero_paladin.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger: {
    source: require('./sprites/1bit/hero_ranger.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue: {
    source: require('./sprites/1bit/hero_rogue.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock: {
    source: require('./sprites/1bit/hero_warlock.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>;

export const SCENES = {
  scene_bad: {
    source: require('./scenes/scene_bad.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_death: {
    source: require('./scenes/scene_death.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_good: {
    source: require('./scenes/scene_good.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_perfect: {
    source: require('./scenes/scene_perfect.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_resurrection: {
    source: require('./scenes/scene_resurrection.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_terrible: {
    source: require('./scenes/scene_terrible.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
} as const satisfies Record<string, SpriteEntry>;

export const ICONS = {
  app_icon: {
    source: require('./icons/app_icon.png'),
    width: 1024,
    height: 1024,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 1024,
  },
  art_alarm_bell: {
    source: require('./icons/art_alarm_bell.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_coffee_amulet: {
    source: require('./icons/art_coffee_amulet.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_hourglass: {
    source: require('./icons/art_hourglass.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_iron_armor: {
    source: require('./icons/art_iron_armor.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_lucky_coin: {
    source: require('./icons/art_lucky_coin.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_night_watch: {
    source: require('./icons/art_night_watch.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_phoenix_feather: {
    source: require('./icons/art_phoenix_feather.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_second_wind: {
    source: require('./icons/art_second_wind.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_star_map: {
    source: require('./icons/art_star_map.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_warm_blanket: {
    source: require('./icons/art_warm_blanket.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_aura: {
    source: require('./icons/cos_aura.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_crown: {
    source: require('./icons/cos_crown.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_frame: {
    source: require('./icons/cos_frame.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_hat: {
    source: require('./icons/cos_hat.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_mask: {
    source: require('./icons/cos_mask.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_pet: {
    source: require('./icons/cos_pet.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_plant: {
    source: require('./icons/cos_plant.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_scarf: {
    source: require('./icons/cos_scarf.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_armor: {
    source: require('./icons/heart_armor.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_empty: {
    source: require('./icons/heart_empty.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_full: {
    source: require('./icons/heart_full.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  logo: {
    source: require('./icons/logo.png'),
    width: 1024,
    height: 1024,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 1024,
  },
  tether_bar: {
    source: require('./icons/tether_bar.png'),
    width: 1024,
    height: 128,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 128,
  },
  tether_cursor: {
    source: require('./icons/tether_cursor.png'),
    width: 64,
    height: 128,
    frames: 1,
    frameWidth: 64,
    frameHeight: 128,
  },
  tether_zone: {
    source: require('./icons/tether_zone.png'),
    width: 1024,
    height: 128,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 128,
  },
  tile_black: {
    source: require('./icons/tile_black.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
  tile_gold: {
    source: require('./icons/tile_gold.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
  tile_gray: {
    source: require('./icons/tile_gray.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
} as const satisfies Record<string, SpriteEntry>;

export const AUDIO = {
  music_day: {
    source: require('./audio/music_day.wav'),
    durationSec: 13.584761904761905,
    loop: true,
  },
  music_night: {
    source: require('./audio/music_night.wav'),
    durationSec: 13.714285714285714,
    loop: true,
  },
  sfx_chest: { source: require('./audio/sfx_chest.wav'), durationSec: 0.8, loop: false },
  sfx_damage: {
    source: require('./audio/sfx_damage.wav'),
    durationSec: 0.24997732426303854,
    loop: false,
  },
  sfx_death: { source: require('./audio/sfx_death.wav'), durationSec: 1.5, loop: false },
  sfx_victory: { source: require('./audio/sfx_victory.wav'), durationSec: 2.0, loop: false },
} as const satisfies Record<string, AudioEntry>;
