/* eslint-disable max-lines */
// GENERATED FILE — produced by tools/pixelate.py / tools/generate_audio.py.
// Do not edit by hand; rerun the pipeline instead. This manifest is the ONLY
// supported way for UI code to reference game assets (PROMPT C §6).
//
// Multi-frame assets are horizontal strips: frameWidth x frameHeight per
// frame, `frames` frames laid out left to right.

export interface SpriteEntry {
  /** Metro asset reference — pass straight to <Image source={...} />. */
  readonly source: number
  /** On-disk pixel size of the whole strip (grid size x 4 upscale). */
  readonly width: number
  readonly height: number
  readonly frames: number
  readonly frameWidth: number
  readonly frameHeight: number
}

export interface AudioEntry {
  readonly source: number
  readonly durationSec: number
  readonly loop: boolean
}

export const SPRITES = {
  chest: {
    source: require('./pixellab/sprites/chest.png'),
    width: 576,
    height: 192,
    frames: 3,
    frameWidth: 192,
    frameHeight: 192,
  },
  gravestone: {
    source: require('./pixellab/sprites/gravestone.png'),
    width: 192,
    height: 192,
    frames: 1,
    frameWidth: 192,
    frameHeight: 192,
  },
  guide_luma: {
    source: require('./pixellab/sprites/guide_luma.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid: {
    source: require('./pixellab/sprites/hero_druid.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_gold: {
    source: require('./pixellab/sprites/hero_druid_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_gold_walk: {
    source: require('./pixellab/sprites/hero_druid_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_walk: {
    source: require('./pixellab/sprites/hero_druid_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight: {
    source: require('./pixellab/sprites/hero_knight.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_gold: {
    source: require('./pixellab/sprites/hero_knight_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_gold_walk: {
    source: require('./pixellab/sprites/hero_knight_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_walk: {
    source: require('./pixellab/sprites/hero_knight_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage: {
    source: require('./pixellab/sprites/hero_mage.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_gold: {
    source: require('./pixellab/sprites/hero_mage_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_gold_walk: {
    source: require('./pixellab/sprites/hero_mage_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_walk: {
    source: require('./pixellab/sprites/hero_mage_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk: {
    source: require('./pixellab/sprites/hero_monk.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_gold: {
    source: require('./pixellab/sprites/hero_monk_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_gold_walk: {
    source: require('./pixellab/sprites/hero_monk_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_walk: {
    source: require('./pixellab/sprites/hero_monk_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja: {
    source: require('./pixellab/sprites/hero_ninja.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_gold: {
    source: require('./pixellab/sprites/hero_ninja_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_gold_walk: {
    source: require('./pixellab/sprites/hero_ninja_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_walk: {
    source: require('./pixellab/sprites/hero_ninja_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin: {
    source: require('./pixellab/sprites/hero_paladin.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_gold: {
    source: require('./pixellab/sprites/hero_paladin_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_gold_walk: {
    source: require('./pixellab/sprites/hero_paladin_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_walk: {
    source: require('./pixellab/sprites/hero_paladin_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger: {
    source: require('./pixellab/sprites/hero_ranger.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_gold: {
    source: require('./pixellab/sprites/hero_ranger_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_gold_walk: {
    source: require('./pixellab/sprites/hero_ranger_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_walk: {
    source: require('./pixellab/sprites/hero_ranger_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue: {
    source: require('./pixellab/sprites/hero_rogue.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_gold: {
    source: require('./pixellab/sprites/hero_rogue_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_gold_walk: {
    source: require('./pixellab/sprites/hero_rogue_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_walk: {
    source: require('./pixellab/sprites/hero_rogue_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock: {
    source: require('./pixellab/sprites/hero_warlock.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_gold: {
    source: require('./pixellab/sprites/hero_warlock_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_gold_walk: {
    source: require('./pixellab/sprites/hero_warlock_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_walk: {
    source: require('./pixellab/sprites/hero_warlock_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>

export const SPRITES_1BIT = {
  '1bit_heart_empty': {
    source: require('./pixellab/sprites/1bit/1bit_heart_empty.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  '1bit_heart_full': {
    source: require('./pixellab/sprites/1bit/1bit_heart_full.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  hero_druid: {
    source: require('./pixellab/sprites/1bit/hero_druid.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_walk: {
    source: require('./pixellab/sprites/1bit/hero_druid_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_icon_40: {
    source: require('./pixellab/sprites/1bit/hero_icon_40.png'),
    width: 160,
    height: 160,
    frames: 1,
    frameWidth: 160,
    frameHeight: 160,
  },
  hero_knight: {
    source: require('./pixellab/sprites/1bit/hero_knight.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_walk: {
    source: require('./pixellab/sprites/1bit/hero_knight_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage: {
    source: require('./pixellab/sprites/1bit/hero_mage.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_walk: {
    source: require('./pixellab/sprites/1bit/hero_mage_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk: {
    source: require('./pixellab/sprites/1bit/hero_monk.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_walk: {
    source: require('./pixellab/sprites/1bit/hero_monk_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja: {
    source: require('./pixellab/sprites/1bit/hero_ninja.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_walk: {
    source: require('./pixellab/sprites/1bit/hero_ninja_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin: {
    source: require('./pixellab/sprites/1bit/hero_paladin.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_walk: {
    source: require('./pixellab/sprites/1bit/hero_paladin_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger: {
    source: require('./pixellab/sprites/1bit/hero_ranger.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_walk: {
    source: require('./pixellab/sprites/1bit/hero_ranger_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue: {
    source: require('./pixellab/sprites/1bit/hero_rogue.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_walk: {
    source: require('./pixellab/sprites/1bit/hero_rogue_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock: {
    source: require('./pixellab/sprites/1bit/hero_warlock.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_walk: {
    source: require('./pixellab/sprites/1bit/hero_warlock_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>

export const SCENES = {
  scene_bad: {
    source: require('./pixellab/scenes/scene_bad.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_death: {
    source: require('./pixellab/scenes/scene_death.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_good: {
    source: require('./pixellab/scenes/scene_good.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_perfect: {
    source: require('./pixellab/scenes/scene_perfect.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_resurrection: {
    source: require('./pixellab/scenes/scene_resurrection.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_terrible: {
    source: require('./pixellab/scenes/scene_terrible.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  start_bag_pressed: {
    source: require('./start_screen/bag_pressed.png'),
    width: 210,
    height: 170,
    frames: 1,
    frameWidth: 210,
    frameHeight: 170,
  },
  start_book_frame_1: {
    source: require('./start_screen/book_frame_1.png'),
    width: 2160,
    height: 3840,
    frames: 1,
    frameWidth: 2160,
    frameHeight: 3840,
  },
  start_mosaic_pressed: {
    source: require('./start_screen/mosaic_pressed.png'),
    width: 210,
    height: 170,
    frames: 1,
    frameWidth: 210,
    frameHeight: 170,
  },
  start_settings_pressed: {
    source: require('./start_screen/settings_pressed.png'),
    width: 205,
    height: 170,
    frames: 1,
    frameWidth: 205,
    frameHeight: 170,
  },
  start_sleep_pressed: {
    source: require('./start_screen/sleep_pressed.png'),
    width: 595,
    height: 165,
    frames: 1,
    frameWidth: 595,
    frameHeight: 165,
  },
} as const satisfies Record<string, SpriteEntry>

export const ICONS = {
  app_icon: {
    source: require('./pixellab/icons/app_icon.png'),
    width: 1024,
    height: 1024,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 1024,
  },
  art_alarm_bell: {
    source: require('./pixellab/icons/art_alarm_bell.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_coffee_amulet: {
    source: require('./pixellab/icons/art_coffee_amulet.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_hourglass: {
    source: require('./pixellab/icons/art_hourglass.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_iron_armor: {
    source: require('./pixellab/icons/art_iron_armor.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_lucky_coin: {
    source: require('./pixellab/icons/art_lucky_coin.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_night_watch: {
    source: require('./pixellab/icons/art_night_watch.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_phoenix_feather: {
    source: require('./pixellab/icons/art_phoenix_feather.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_second_wind: {
    source: require('./pixellab/icons/art_second_wind.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_star_map: {
    source: require('./pixellab/icons/art_star_map.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_warm_blanket: {
    source: require('./pixellab/icons/art_warm_blanket.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  book_cover: {
    source: require('./pixellab/icons/book_cover.png'),
    width: 320,
    height: 416,
    frames: 1,
    frameWidth: 320,
    frameHeight: 416,
  },
  book_open: {
    source: require('./pixellab/icons/book_open.png'),
    width: 400,
    height: 352,
    frames: 1,
    frameWidth: 400,
    frameHeight: 352,
  },
  cos_aura: {
    source: require('./pixellab/icons/cos_aura.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_crown: {
    source: require('./pixellab/icons/cos_crown.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_frame: {
    source: require('./pixellab/icons/cos_frame.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_hat: {
    source: require('./pixellab/icons/cos_hat.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_mask: {
    source: require('./pixellab/icons/cos_mask.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_pet: {
    source: require('./pixellab/icons/cos_pet.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_plant: {
    source: require('./pixellab/icons/cos_plant.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_scarf: {
    source: require('./pixellab/icons/cos_scarf.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  guide_moon_crest: {
    source: require('./pixellab/icons/guide_moon_crest.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  guide_sleep_book: {
    source: require('./pixellab/icons/guide_sleep_book.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_armor: {
    source: require('./pixellab/icons/heart_armor.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_empty: {
    source: require('./pixellab/icons/heart_empty.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_full: {
    source: require('./pixellab/icons/heart_full.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  logo: {
    source: require('./pixellab/icons/logo.png'),
    width: 1024,
    height: 1024,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 1024,
  },
  tether_bar: {
    source: require('./icons/tether_bar.png'),
    width: 1024,
    height: 128,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 128,
  },
  tether_cursor: {
    source: require('./icons/tether_cursor.png'),
    width: 64,
    height: 128,
    frames: 1,
    frameWidth: 64,
    frameHeight: 128,
  },
  tether_zone: {
    source: require('./icons/tether_zone.png'),
    width: 1024,
    height: 128,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 128,
  },
  tile_black: {
    source: require('./icons/tile_black.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
  tile_gold: {
    source: require('./icons/tile_gold.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
  tile_gray: {
    source: require('./icons/tile_gray.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
} as const satisfies Record<string, SpriteEntry>

export const ATMO = {
  big_tree_night: {
    source: require('./pixellab/atmo/big_tree_night.png'),
    width: 358,
    height: 438,
    frames: 1,
    frameWidth: 358,
    frameHeight: 438,
  },
  cloud_a_day: {
    source: require('./pixellab/atmo/cloud_a_day.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_a_evening: {
    source: require('./pixellab/atmo/cloud_a_evening.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_a_morning: {
    source: require('./pixellab/atmo/cloud_a_morning.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_a_night: {
    source: require('./pixellab/atmo/cloud_a_night.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_b_day: {
    source: require('./pixellab/atmo/cloud_b_day.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  cloud_b_evening: {
    source: require('./pixellab/atmo/cloud_b_evening.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  cloud_b_morning: {
    source: require('./pixellab/atmo/cloud_b_morning.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  cloud_b_night: {
    source: require('./pixellab/atmo/cloud_b_night.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  cloud_night_a: {
    source: require('./pixellab/atmo/cloud_night_a.png'),
    width: 212,
    height: 34,
    frames: 1,
    frameWidth: 212,
    frameHeight: 34,
  },
  cloud_night_b: {
    source: require('./pixellab/atmo/cloud_night_b.png'),
    width: 144,
    height: 52,
    frames: 1,
    frameWidth: 144,
    frameHeight: 52,
  },
  grass_day: {
    source: require('./pixellab/atmo/grass_day.png'),
    width: 384,
    height: 210,
    frames: 1,
    frameWidth: 384,
    frameHeight: 210,
  },
  grass_evening: {
    source: require('./pixellab/atmo/grass_evening.png'),
    width: 384,
    height: 210,
    frames: 1,
    frameWidth: 384,
    frameHeight: 210,
  },
  grass_morning: {
    source: require('./pixellab/atmo/grass_morning.png'),
    width: 384,
    height: 210,
    frames: 1,
    frameWidth: 384,
    frameHeight: 210,
  },
  grass_night: {
    source: require('./pixellab/atmo/grass_night.png'),
    width: 384,
    height: 96,
    frames: 1,
    frameWidth: 384,
    frameHeight: 96,
  },
  leaf_a: {
    source: require('./pixellab/atmo/leaf_a.png'),
    width: 34,
    height: 38,
    frames: 1,
    frameWidth: 34,
    frameHeight: 38,
  },
  leaf_b: {
    source: require('./pixellab/atmo/leaf_b.png'),
    width: 24,
    height: 50,
    frames: 1,
    frameWidth: 24,
    frameHeight: 50,
  },
  moon_full: {
    source: require('./pixellab/atmo/moon_full.png'),
    width: 204,
    height: 204,
    frames: 1,
    frameWidth: 204,
    frameHeight: 204,
  },
  moon_night: {
    source: require('./pixellab/atmo/moon_night.png'),
    width: 200,
    height: 198,
    frames: 1,
    frameWidth: 200,
    frameHeight: 198,
  },
  mountains_night: {
    source: require('./pixellab/atmo/mountains_night.png'),
    width: 768,
    height: 121,
    frames: 1,
    frameWidth: 768,
    frameHeight: 121,
  },
  pines_night: {
    source: require('./pixellab/atmo/pines_night.png'),
    width: 768,
    height: 128,
    frames: 1,
    frameWidth: 768,
    frameHeight: 128,
  },
  prop_bush: {
    source: require('./pixellab/atmo/prop_bush.png'),
    width: 84,
    height: 84,
    frames: 1,
    frameWidth: 84,
    frameHeight: 84,
  },
  prop_campfire: {
    source: require('./pixellab/atmo/prop_campfire.png'),
    width: 80,
    height: 74,
    frames: 1,
    frameWidth: 80,
    frameHeight: 74,
  },
  prop_castle: {
    source: require('./pixellab/atmo/prop_castle.png'),
    width: 224,
    height: 258,
    frames: 1,
    frameWidth: 224,
    frameHeight: 258,
  },
  prop_crystal: {
    source: require('./pixellab/atmo/prop_crystal.png'),
    width: 106,
    height: 106,
    frames: 1,
    frameWidth: 106,
    frameHeight: 106,
  },
  prop_fence: {
    source: require('./pixellab/atmo/prop_fence.png'),
    width: 106,
    height: 70,
    frames: 1,
    frameWidth: 106,
    frameHeight: 70,
  },
  prop_lantern: {
    source: require('./pixellab/atmo/prop_lantern.png'),
    width: 48,
    height: 142,
    frames: 1,
    frameWidth: 48,
    frameHeight: 142,
  },
  prop_mushrooms: {
    source: require('./pixellab/atmo/prop_mushrooms.png'),
    width: 80,
    height: 74,
    frames: 1,
    frameWidth: 80,
    frameHeight: 74,
  },
  prop_runestone: {
    source: require('./pixellab/atmo/prop_runestone.png'),
    width: 124,
    height: 168,
    frames: 1,
    frameWidth: 124,
    frameHeight: 168,
  },
  prop_stump_owl: {
    source: require('./pixellab/atmo/prop_stump_owl.png'),
    width: 88,
    height: 126,
    frames: 1,
    frameWidth: 88,
    frameHeight: 126,
  },
  prop_windmill: {
    source: require('./pixellab/atmo/prop_windmill.png'),
    width: 192,
    height: 226,
    frames: 1,
    frameWidth: 192,
    frameHeight: 226,
  },
  sun_day: {
    source: require('./pixellab/atmo/sun_day.png'),
    width: 256,
    height: 256,
    frames: 1,
    frameWidth: 256,
    frameHeight: 256,
  },
  sun_evening: {
    source: require('./pixellab/atmo/sun_evening.png'),
    width: 256,
    height: 256,
    frames: 1,
    frameWidth: 256,
    frameHeight: 256,
  },
  sun_morning: {
    source: require('./pixellab/atmo/sun_morning.png'),
    width: 256,
    height: 256,
    frames: 1,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>

export const DESIGN = {
  bag_button_close: {
    source: require('./design/bag/gen/button_close.png'),
    width: 1200,
    height: 380,
    frames: 1,
    frameWidth: 1200,
    frameHeight: 380,
  },
  bag_panel_consumables: {
    source: require('./design/bag/gen/panel_consumables.png'),
    width: 1920,
    height: 1540,
    frames: 1,
    frameWidth: 1920,
    frameHeight: 1540,
  },
  bag_slot_empty: {
    source: require('./design/bag/gen/slot_empty.png'),
    width: 840,
    height: 870,
    frames: 1,
    frameWidth: 840,
    frameHeight: 870,
  },
  bag_slot_frame: {
    source: require('./design/bag/gen/slot_frame.png'),
    width: 840,
    height: 870,
    frames: 1,
    frameWidth: 840,
    frameHeight: 870,
  },
  bag_title: {
    source: require('./design/bag/gen/title.png'),
    width: 1648,
    height: 201,
    frames: 1,
    frameWidth: 1648,
    frameHeight: 201,
  },
  chest_button_claim: {
    source: require('./design/chest/30-button-claim.png'),
    width: 626,
    height: 186,
    frames: 1,
    frameWidth: 626,
    frameHeight: 186,
  },
  chest_candle_l: {
    source: require('./design/chest/23-candle-l.png'),
    width: 110,
    height: 310,
    frames: 1,
    frameWidth: 110,
    frameHeight: 310,
  },
  chest_candle_r: {
    source: require('./design/chest/24-candle-r.png'),
    width: 158,
    height: 310,
    frames: 1,
    frameWidth: 158,
    frameHeight: 310,
  },
  chest_card_frame: {
    source: require('./design/chest/28-card-frame.png'),
    width: 522,
    height: 626,
    frames: 1,
    frameWidth: 522,
    frameHeight: 626,
  },
  chest_chest_gold: {
    source: require('./design/chest/34-chest-gold.png'),
    width: 626,
    height: 544,
    frames: 1,
    frameWidth: 626,
    frameHeight: 544,
  },
  chest_chest_open_glow: {
    source: require('./design/chest/29-chest-open-glow.png'),
    width: 612,
    height: 486,
    frames: 1,
    frameWidth: 612,
    frameHeight: 486,
  },
  chest_chest_steel: {
    source: require('./design/chest/22-chest-steel.png'),
    width: 626,
    height: 478,
    frames: 1,
    frameWidth: 626,
    frameHeight: 478,
  },
  chest_plaque_ready: {
    source: require('./design/chest/21-plaque-ready.png'),
    width: 582,
    height: 154,
    frames: 1,
    frameWidth: 582,
    frameHeight: 154,
  },
  chest_ribbon_lucky: {
    source: require('./design/chest/35-ribbon-lucky.png'),
    width: 622,
    height: 90,
    frames: 1,
    frameWidth: 622,
    frameHeight: 90,
  },
  chest_ribbon_rare: {
    source: require('./design/chest/27-ribbon-rare.png'),
    width: 382,
    height: 146,
    frames: 1,
    frameWidth: 382,
    frameHeight: 146,
  },
  chest_sparkle_1: {
    source: require('./design/chest/31-sparkle-1.png'),
    width: 38,
    height: 42,
    frames: 1,
    frameWidth: 38,
    frameHeight: 42,
  },
  chest_title_weekly_chest: {
    source: require('./design/chest/20-title-weekly-chest.png'),
    width: 622,
    height: 156,
    frames: 1,
    frameWidth: 622,
    frameHeight: 156,
  },
  chest_title_weekly_chest_gold: {
    source: require('./design/chest/33-title-weekly-chest-gold.png'),
    width: 612,
    height: 158,
    frames: 1,
    frameWidth: 612,
    frameHeight: 158,
  },
  chest_title_weekly_loot: {
    source: require('./design/chest/26-title-weekly-loot.png'),
    width: 612,
    height: 128,
    frames: 1,
    frameWidth: 612,
    frameHeight: 128,
  },
  gen_book_page_right_crop: {
    source: require('./design/gen/book_page_right_crop.png'),
    width: 244,
    height: 233,
    frames: 1,
    frameWidth: 244,
    frameHeight: 233,
  },
  gen_booktransition_scene: {
    source: require('./design/gen/booktransition_scene.png'),
    width: 256,
    height: 352,
    frames: 1,
    frameWidth: 256,
    frameHeight: 352,
  },
  gen_chest_open_scene: {
    source: require('./design/gen/chest_open_scene.png'),
    width: 200,
    height: 168,
    frames: 1,
    frameWidth: 200,
    frameHeight: 168,
  },
  gen_heroes_bust_druid: {
    source: require('./design/gen/heroes_bust_druid.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_knight: {
    source: require('./design/gen/heroes_bust_knight.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_mage: {
    source: require('./design/gen/heroes_bust_mage.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_monk: {
    source: require('./design/gen/heroes_bust_monk.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_ninja: {
    source: require('./design/gen/heroes_bust_ninja.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_paladin: {
    source: require('./design/gen/heroes_bust_paladin.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_ranger: {
    source: require('./design/gen/heroes_bust_ranger.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_rogue: {
    source: require('./design/gen/heroes_bust_rogue.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_heroes_bust_warlock: {
    source: require('./design/gen/heroes_bust_warlock.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  gen_tutorial_p1: {
    source: require('./design/gen/tutorial_p1.png'),
    width: 160,
    height: 160,
    frames: 1,
    frameWidth: 160,
    frameHeight: 160,
  },
  gen_tutorial_p2: {
    source: require('./design/gen/tutorial_p2.png'),
    width: 160,
    height: 160,
    frames: 1,
    frameWidth: 160,
    frameHeight: 160,
  },
  gen_tutorial_p3: {
    source: require('./design/gen/tutorial_p3.png'),
    width: 160,
    height: 160,
    frames: 1,
    frameWidth: 160,
    frameHeight: 160,
  },
  onboarding_button_begin_plaque: {
    source: require('./design/onboarding/17-button-begin-plaque.png'),
    width: 1558,
    height: 452,
    frames: 1,
    frameWidth: 1558,
    frameHeight: 452,
  },
  onboarding_caption_min_hours: {
    source: require('./design/onboarding/18-caption-min-hours.png'),
    width: 874,
    height: 70,
    frames: 1,
    frameWidth: 874,
    frameHeight: 70,
  },
  onboarding_logo_text: {
    source: require('./design/onboarding/15-logo-text.png'),
    width: 1508,
    height: 774,
    frames: 1,
    frameWidth: 1508,
    frameHeight: 774,
  },
  onboarding_panel_rules_card: {
    source: require('./design/onboarding/16-panel-rules-card.png'),
    width: 1848,
    height: 1028,
    frames: 1,
    frameWidth: 1848,
    frameHeight: 1028,
  },
  onboarding_picker_window_bedtime: {
    source: require('./design/onboarding/12-picker-window-bedtime.png'),
    width: 282,
    height: 364,
    frames: 1,
    frameWidth: 282,
    frameHeight: 364,
  },
  onboarding_picker_window_wakeup: {
    source: require('./design/onboarding/13-picker-window-wakeup.png'),
    width: 282,
    height: 364,
    frames: 1,
    frameWidth: 282,
    frameHeight: 364,
  },
  onboarding_selection_arrow: {
    source: require('./design/onboarding/14-selection-arrow.png'),
    width: 32,
    height: 40,
    frames: 1,
    frameWidth: 32,
    frameHeight: 40,
  },
  settings_header: {
    source: require('./design/settings/header.png'),
    width: 1960,
    height: 340,
    frames: 1,
    frameWidth: 1960,
    frameHeight: 340,
  },
  settings_row_blank: {
    source: require('./design/settings/row_blank.png'),
    width: 2026,
    height: 440,
    frames: 1,
    frameWidth: 2026,
    frameHeight: 440,
  },
  settings_row_change: {
    source: require('./design/settings/row_change.png'),
    width: 2026,
    height: 444,
    frames: 1,
    frameWidth: 2026,
    frameHeight: 444,
  },
  settings_row_eink: {
    source: require('./design/settings/row_eink.png'),
    width: 2026,
    height: 442,
    frames: 1,
    frameWidth: 2026,
    frameHeight: 442,
  },
  settings_row_eink_off: {
    source: require('./design/settings/row_eink_off.png'),
    width: 2026,
    height: 442,
    frames: 1,
    frameWidth: 2026,
    frameHeight: 442,
  },
  settings_row_notif: {
    source: require('./design/settings/row_notif.png'),
    width: 2026,
    height: 444,
    frames: 1,
    frameWidth: 2026,
    frameHeight: 444,
  },
  settings_row_reset: {
    source: require('./design/settings/row_reset.png'),
    width: 2026,
    height: 454,
    frames: 1,
    frameWidth: 2026,
    frameHeight: 454,
  },
  settings_row_window: {
    source: require('./design/settings/row_window.png'),
    width: 2026,
    height: 440,
    frames: 1,
    frameWidth: 2026,
    frameHeight: 440,
  },
  settings_toggle_knob: {
    source: require('./design/settings/toggle_knob.png'),
    width: 295,
    height: 245,
    frames: 1,
    frameWidth: 295,
    frameHeight: 245,
  },
  settings_toggle_knob_blank: {
    source: require('./design/settings/toggle_knob_blank.png'),
    width: 295,
    height: 245,
    frames: 1,
    frameWidth: 295,
    frameHeight: 245,
  },
  settings_toggle_track: {
    source: require('./design/settings/toggle_track.png'),
    width: 461,
    height: 216,
    frames: 1,
    frameWidth: 461,
    frameHeight: 216,
  },
  settings_version: {
    source: require('./design/settings/version.png'),
    width: 610,
    height: 80,
    frames: 1,
    frameWidth: 610,
    frameHeight: 80,
  },
} as const satisfies Record<string, SpriteEntry>

export const LUMA = {
  btn_accept: {
    source: require('./luma/btn_accept.png'),
    width: 703,
    height: 162,
    frames: 1,
    frameWidth: 703,
    frameHeight: 162,
  },
  btn_accept_down: {
    source: require('./luma/btn_accept_down.png'),
    width: 703,
    height: 162,
    frames: 1,
    frameWidth: 703,
    frameHeight: 162,
  },
  btn_adjust: {
    source: require('./luma/btn_adjust.png'),
    width: 424,
    height: 115,
    frames: 1,
    frameWidth: 424,
    frameHeight: 115,
  },
  btn_adjust_down: {
    source: require('./luma/btn_adjust_down.png'),
    width: 424,
    height: 115,
    frames: 1,
    frameWidth: 424,
    frameHeight: 115,
  },
  btn_empty: {
    source: require('./luma/btn_empty.png'),
    width: 959,
    height: 129,
    frames: 1,
    frameWidth: 959,
    frameHeight: 129,
  },
  btn_empty_down: {
    source: require('./luma/btn_empty_down.png'),
    width: 959,
    height: 129,
    frames: 1,
    frameWidth: 959,
    frameHeight: 129,
  },
  morning_base: {
    source: require('./luma/morning_base.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  morning_blink: {
    source: require('./luma/morning_blink.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  morning_env2: {
    source: require('./luma/morning_env2.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  morning_env3: {
    source: require('./luma/morning_env3.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  morning_talk_half: {
    source: require('./luma/morning_talk_half.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  morning_talk_open: {
    source: require('./luma/morning_talk_open.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_base: {
    source: require('./luma/s1_base.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_base_start: {
    source: require('./luma/s1_base_start.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_blink: {
    source: require('./luma/s1_blink.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_blink_start: {
    source: require('./luma/s1_blink_start.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_env2: {
    source: require('./luma/s1_env2.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_env2_start: {
    source: require('./luma/s1_env2_start.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_env3: {
    source: require('./luma/s1_env3.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_env3_start: {
    source: require('./luma/s1_env3_start.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_env4: {
    source: require('./luma/s1_env4.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_env4_start: {
    source: require('./luma/s1_env4_start.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_talk_half: {
    source: require('./luma/s1_talk_half.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_talk_half_start: {
    source: require('./luma/s1_talk_half_start.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_talk_open: {
    source: require('./luma/s1_talk_open.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s1_talk_open_start: {
    source: require('./luma/s1_talk_open_start.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s2_base: {
    source: require('./luma/s2_base.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s2_blink: {
    source: require('./luma/s2_blink.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s2_env2: {
    source: require('./luma/s2_env2.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
  s2_env3: {
    source: require('./luma/s2_env3.png'),
    width: 1080,
    height: 1920,
    frames: 1,
    frameWidth: 1080,
    frameHeight: 1920,
  },
} as const satisfies Record<string, SpriteEntry>

export const AUDIO = {
  music_day: { source: require('./audio/day_theme.mp3'), durationSec: 14.4, loop: true },
  music_night: { source: require('./audio/main_theme.mp3'), durationSec: 16.0, loop: true },
  sfx_chest: { source: require('./audio/sfx_chest.wav'), durationSec: 0.8, loop: false },
  sfx_damage: {
    source: require('./audio/sfx_damage.wav'),
    durationSec: 0.24997732426303854,
    loop: false,
  },
  sfx_death: { source: require('./audio/sfx_death.wav'), durationSec: 1.5, loop: false },
  sfx_victory: { source: require('./audio/sfx_victory.wav'), durationSec: 2.0, loop: false },
} as const satisfies Record<string, AudioEntry>
