// GENERATED FILE — produced by tools/pixelate.py / tools/generate_audio.py.
// Do not edit by hand; rerun the pipeline instead. This manifest is the ONLY
// supported way for UI code to reference game assets (PROMPT C §6).
//
// Multi-frame assets are horizontal strips: frameWidth x frameHeight per
// frame, `frames` frames laid out left to right.

export interface SpriteEntry {
  /** Metro asset reference — pass straight to <Image source={...} />. */
  readonly source: number
  /** On-disk pixel size of the whole strip (grid size x 4 upscale). */
  readonly width: number
  readonly height: number
  readonly frames: number
  readonly frameWidth: number
  readonly frameHeight: number
}

export interface AudioEntry {
  readonly source: number
  readonly durationSec: number
  readonly loop: boolean
}

export const SPRITES = {
  chest: {
    source: require('./pixellab/sprites/chest.png'),
    width: 576,
    height: 192,
    frames: 3,
    frameWidth: 192,
    frameHeight: 192,
  },
  gravestone: {
    source: require('./pixellab/sprites/gravestone.png'),
    width: 192,
    height: 192,
    frames: 1,
    frameWidth: 192,
    frameHeight: 192,
  },
  hero_druid: {
    source: require('./pixellab/sprites/hero_druid.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_gold: {
    source: require('./pixellab/sprites/hero_druid_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_gold_walk: {
    source: require('./pixellab/sprites/hero_druid_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_walk: {
    source: require('./pixellab/sprites/hero_druid_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight: {
    source: require('./pixellab/sprites/hero_knight.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_gold: {
    source: require('./pixellab/sprites/hero_knight_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_gold_walk: {
    source: require('./pixellab/sprites/hero_knight_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_walk: {
    source: require('./pixellab/sprites/hero_knight_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage: {
    source: require('./pixellab/sprites/hero_mage.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_gold: {
    source: require('./pixellab/sprites/hero_mage_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_gold_walk: {
    source: require('./pixellab/sprites/hero_mage_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_walk: {
    source: require('./pixellab/sprites/hero_mage_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk: {
    source: require('./pixellab/sprites/hero_monk.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_gold: {
    source: require('./pixellab/sprites/hero_monk_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_gold_walk: {
    source: require('./pixellab/sprites/hero_monk_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_walk: {
    source: require('./pixellab/sprites/hero_monk_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja: {
    source: require('./pixellab/sprites/hero_ninja.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_gold: {
    source: require('./pixellab/sprites/hero_ninja_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_gold_walk: {
    source: require('./pixellab/sprites/hero_ninja_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_walk: {
    source: require('./pixellab/sprites/hero_ninja_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin: {
    source: require('./pixellab/sprites/hero_paladin.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_gold: {
    source: require('./pixellab/sprites/hero_paladin_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_gold_walk: {
    source: require('./pixellab/sprites/hero_paladin_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_walk: {
    source: require('./pixellab/sprites/hero_paladin_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger: {
    source: require('./pixellab/sprites/hero_ranger.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_gold: {
    source: require('./pixellab/sprites/hero_ranger_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_gold_walk: {
    source: require('./pixellab/sprites/hero_ranger_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_walk: {
    source: require('./pixellab/sprites/hero_ranger_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue: {
    source: require('./pixellab/sprites/hero_rogue.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_gold: {
    source: require('./pixellab/sprites/hero_rogue_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_gold_walk: {
    source: require('./pixellab/sprites/hero_rogue_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_walk: {
    source: require('./pixellab/sprites/hero_rogue_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock: {
    source: require('./pixellab/sprites/hero_warlock.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_gold: {
    source: require('./pixellab/sprites/hero_warlock_gold.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_gold_walk: {
    source: require('./pixellab/sprites/hero_warlock_gold_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_walk: {
    source: require('./pixellab/sprites/hero_warlock_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>

export const SPRITES_1BIT = {
  '1bit_heart_empty': {
    source: require('./pixellab/sprites/1bit/1bit_heart_empty.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  '1bit_heart_full': {
    source: require('./pixellab/sprites/1bit/1bit_heart_full.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  hero_druid: {
    source: require('./pixellab/sprites/1bit/hero_druid.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_druid_walk: {
    source: require('./pixellab/sprites/1bit/hero_druid_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_icon_40: {
    source: require('./pixellab/sprites/1bit/hero_icon_40.png'),
    width: 160,
    height: 160,
    frames: 1,
    frameWidth: 160,
    frameHeight: 160,
  },
  hero_knight: {
    source: require('./pixellab/sprites/1bit/hero_knight.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_knight_walk: {
    source: require('./pixellab/sprites/1bit/hero_knight_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage: {
    source: require('./pixellab/sprites/1bit/hero_mage.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_mage_walk: {
    source: require('./pixellab/sprites/1bit/hero_mage_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk: {
    source: require('./pixellab/sprites/1bit/hero_monk.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_monk_walk: {
    source: require('./pixellab/sprites/1bit/hero_monk_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja: {
    source: require('./pixellab/sprites/1bit/hero_ninja.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ninja_walk: {
    source: require('./pixellab/sprites/1bit/hero_ninja_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin: {
    source: require('./pixellab/sprites/1bit/hero_paladin.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_paladin_walk: {
    source: require('./pixellab/sprites/1bit/hero_paladin_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger: {
    source: require('./pixellab/sprites/1bit/hero_ranger.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_ranger_walk: {
    source: require('./pixellab/sprites/1bit/hero_ranger_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue: {
    source: require('./pixellab/sprites/1bit/hero_rogue.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_rogue_walk: {
    source: require('./pixellab/sprites/1bit/hero_rogue_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock: {
    source: require('./pixellab/sprites/1bit/hero_warlock.png'),
    width: 512,
    height: 256,
    frames: 2,
    frameWidth: 256,
    frameHeight: 256,
  },
  hero_warlock_walk: {
    source: require('./pixellab/sprites/1bit/hero_warlock_walk.png'),
    width: 1536,
    height: 256,
    frames: 6,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>

export const SCENES = {
  scene_bad: {
    source: require('./pixellab/scenes/scene_bad.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_death: {
    source: require('./pixellab/scenes/scene_death.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_good: {
    source: require('./pixellab/scenes/scene_good.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_perfect: {
    source: require('./pixellab/scenes/scene_perfect.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_resurrection: {
    source: require('./pixellab/scenes/scene_resurrection.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
  scene_terrible: {
    source: require('./pixellab/scenes/scene_terrible.png'),
    width: 3072,
    height: 576,
    frames: 3,
    frameWidth: 1024,
    frameHeight: 576,
  },
} as const satisfies Record<string, SpriteEntry>

export const ICONS = {
  app_icon: {
    source: require('./pixellab/icons/app_icon.png'),
    width: 1024,
    height: 1024,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 1024,
  },
  art_alarm_bell: {
    source: require('./pixellab/icons/art_alarm_bell.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_coffee_amulet: {
    source: require('./pixellab/icons/art_coffee_amulet.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_hourglass: {
    source: require('./pixellab/icons/art_hourglass.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_iron_armor: {
    source: require('./pixellab/icons/art_iron_armor.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_lucky_coin: {
    source: require('./pixellab/icons/art_lucky_coin.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_night_watch: {
    source: require('./pixellab/icons/art_night_watch.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_phoenix_feather: {
    source: require('./pixellab/icons/art_phoenix_feather.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_second_wind: {
    source: require('./pixellab/icons/art_second_wind.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_star_map: {
    source: require('./pixellab/icons/art_star_map.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  art_warm_blanket: {
    source: require('./pixellab/icons/art_warm_blanket.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_aura: {
    source: require('./pixellab/icons/cos_aura.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_crown: {
    source: require('./pixellab/icons/cos_crown.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_frame: {
    source: require('./pixellab/icons/cos_frame.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_hat: {
    source: require('./pixellab/icons/cos_hat.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_mask: {
    source: require('./pixellab/icons/cos_mask.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_pet: {
    source: require('./pixellab/icons/cos_pet.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_plant: {
    source: require('./pixellab/icons/cos_plant.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  cos_scarf: {
    source: require('./pixellab/icons/cos_scarf.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_armor: {
    source: require('./pixellab/icons/heart_armor.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_empty: {
    source: require('./pixellab/icons/heart_empty.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  heart_full: {
    source: require('./pixellab/icons/heart_full.png'),
    width: 64,
    height: 64,
    frames: 1,
    frameWidth: 64,
    frameHeight: 64,
  },
  logo: {
    source: require('./pixellab/icons/logo.png'),
    width: 1024,
    height: 1024,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 1024,
  },
  tether_bar: {
    source: require('./icons/tether_bar.png'),
    width: 1024,
    height: 128,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 128,
  },
  tether_cursor: {
    source: require('./icons/tether_cursor.png'),
    width: 64,
    height: 128,
    frames: 1,
    frameWidth: 64,
    frameHeight: 128,
  },
  tether_zone: {
    source: require('./icons/tether_zone.png'),
    width: 1024,
    height: 128,
    frames: 1,
    frameWidth: 1024,
    frameHeight: 128,
  },
  tile_black: {
    source: require('./icons/tile_black.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
  tile_gold: {
    source: require('./icons/tile_gold.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
  tile_gray: {
    source: require('./icons/tile_gray.png'),
    width: 32,
    height: 32,
    frames: 1,
    frameWidth: 32,
    frameHeight: 32,
  },
} as const satisfies Record<string, SpriteEntry>

export const ATMO = {
  cloud_a_day: {
    source: require('./pixellab/atmo/cloud_a_day.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_a_evening: {
    source: require('./pixellab/atmo/cloud_a_evening.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_a_morning: {
    source: require('./pixellab/atmo/cloud_a_morning.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_a_night: {
    source: require('./pixellab/atmo/cloud_a_night.png'),
    width: 192,
    height: 96,
    frames: 1,
    frameWidth: 192,
    frameHeight: 96,
  },
  cloud_b_day: {
    source: require('./pixellab/atmo/cloud_b_day.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  cloud_b_evening: {
    source: require('./pixellab/atmo/cloud_b_evening.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  cloud_b_morning: {
    source: require('./pixellab/atmo/cloud_b_morning.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  cloud_b_night: {
    source: require('./pixellab/atmo/cloud_b_night.png'),
    width: 128,
    height: 64,
    frames: 1,
    frameWidth: 128,
    frameHeight: 64,
  },
  grass_day: {
    source: require('./pixellab/atmo/grass_day.png'),
    width: 384,
    height: 210,
    frames: 1,
    frameWidth: 384,
    frameHeight: 210,
  },
  grass_evening: {
    source: require('./pixellab/atmo/grass_evening.png'),
    width: 384,
    height: 210,
    frames: 1,
    frameWidth: 384,
    frameHeight: 210,
  },
  grass_morning: {
    source: require('./pixellab/atmo/grass_morning.png'),
    width: 384,
    height: 210,
    frames: 1,
    frameWidth: 384,
    frameHeight: 210,
  },
  grass_night: {
    source: require('./pixellab/atmo/grass_night.png'),
    width: 384,
    height: 210,
    frames: 1,
    frameWidth: 384,
    frameHeight: 210,
  },
  moon_night: {
    source: require('./pixellab/atmo/moon_night.png'),
    width: 256,
    height: 256,
    frames: 1,
    frameWidth: 256,
    frameHeight: 256,
  },
  sun_day: {
    source: require('./pixellab/atmo/sun_day.png'),
    width: 256,
    height: 256,
    frames: 1,
    frameWidth: 256,
    frameHeight: 256,
  },
  sun_evening: {
    source: require('./pixellab/atmo/sun_evening.png'),
    width: 256,
    height: 256,
    frames: 1,
    frameWidth: 256,
    frameHeight: 256,
  },
  sun_morning: {
    source: require('./pixellab/atmo/sun_morning.png'),
    width: 256,
    height: 256,
    frames: 1,
    frameWidth: 256,
    frameHeight: 256,
  },
} as const satisfies Record<string, SpriteEntry>

export const AUDIO = {
  music_day: { source: require('./audio/music_day.wav'), durationSec: 14.4, loop: true },
  music_night: { source: require('./audio/music_night.wav'), durationSec: 16.0, loop: true },
  sfx_chest: { source: require('./audio/sfx_chest.wav'), durationSec: 0.8, loop: false },
  sfx_damage: {
    source: require('./audio/sfx_damage.wav'),
    durationSec: 0.24997732426303854,
    loop: false,
  },
  sfx_death: { source: require('./audio/sfx_death.wav'), durationSec: 1.5, loop: false },
  sfx_victory: { source: require('./audio/sfx_victory.wav'), durationSec: 2.0, loop: false },
} as const satisfies Record<string, AudioEntry>
